spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_db
    password: root
    username: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql